PATH="/usr/local/bin:$(getconf PATH):$PATH"
PATH="./scripts:$PATH"
PATH="$HOME/bin:$PATH"
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
PATH="$PATH:$HOME/.npm-packages/bin"
PATH="$HOME/.yarn/bin:$PATH"
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
