export PATH="./scripts:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="$PATH:$HOME/.npm-packages/bin"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"
